return {
  { import = "specs.colorscheme" },
  { import = "specs.treesitter" },
  { import = "specs.lsp" },
  { import = "specs.completion" },
  { import = "specs.ui.which-key" },
  { import = "specs.ui.snacks" },
  { import = "specs.ui.lualine" },
  { import = "specs.ui.bufferline" },
  { import = "specs.ui.web-devicons" },
  { import = "specs.ui.gitsigns" },
  { import = "specs.ui.flash" },
  { import = "specs.coding.mini-pairs" },
  { import = "specs.coding.mini-ai" },
  { import = "specs.coding.ts-comments" },
}
